language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "3.8-dev"  # 3.8 development branch
  - "nightly"  # nightly build

# Pycodestyle part
# needed to work correctly with Python 3 shebang
env: SKIP_INTERPRETER=true
install:
  - pip install pycodestyle
  - pip install pydocstyle
  - pip install pytest-cov
  - pip install -r requirements.txt
script:
  - make pycodestyle
  - make pydocstyle

script:
  - pytest -v --cov=insights_sha_extractor
